#Genetic algorithm project configuration file
# Be careful to put a comma + a space between each data...! (YAML convention)

#################################################################################
fitness_limit: 0.001
population_path: './test.csv'

maximum_iteration: 500
population_size: 50
number_of_parents: 20

number_of_bits: 64

#Algorithm constants
#mutation is bit flip by default
mutation_rate: 0.001

crossover_rate: 0.6
crossover_type: default


#Selection strategy between
selection_strategy: default

#fitness function
fitness_function: |
    @(x, y)y-x
